version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portalops-backend
    ports:
      - "8000:8000"
    volumes:
       - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7.2-alpine
    container_name: portalops-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portalops-frontend
    ports:
      - "80:80"  # 👈 exposes on your VPS public IP at port 80
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
