"""add content column to ticket

Revision ID: 251e9e095367
Revises: d9e490b63ba5
Create Date: 2025-06-10 12:40:49.804071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251e9e095367'
down_revision: Union[str, None] = 'd9e490b63ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('tickets', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'content')
    # ### end Alembic commands ###
