# Generated by Django 5.2.1 on 2025-06-26 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttype',
            options={'verbose_name': 'Project Type', 'verbose_name_plural': 'Project Types'},
        ),
        migrations.AddField(
            model_name='projecttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='flavor_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
