# Generated by Django 5.2.1 on 2025-07-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projecttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingIPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('subnet_id', models.UUIDField()),
                ('network_id', models.UUIDField()),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('vm_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('reserved', 'Reserved'), ('released', 'Released')], default='available', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'floating_ip_pool',
                'indexes': [models.Index(fields=['subnet_id'], name='floating_ip_subnet__e204f4_idx'), models.Index(fields=['network_id'], name='floating_ip_network_db0570_idx'), models.Index(fields=['status'], name='floating_ip_status_38290b_idx')],
            },
        ),
    ]
