# Generated by Django 5.2.1 on 2025-07-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_floatingippool'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatingippool',
            name='vm_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
