# Generated by Django 5.2.1 on 2025-06-19 01:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_userprofile_status_userprofile_totp_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending2FASession',
            fields=[
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('encrypted_password', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
